# Generated by Django 6.0.2 on 2026-02-12 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('college', 'College'), ('university', 'University')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
