# Generated by Django 6.0.2 on 2026-02-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-votes']},
        ),
    ]
