# Generated by Django 6.0.2 on 2026-03-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_alter_grievance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='priority_notified',
            field=models.BooleanField(default=False),
        ),
    ]
