# Generated by Django 6.0.2 on 2026-03-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0006_grievance_priority_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='priority_notified',
        ),
    ]
