# Generated by Django 6.0.2 on 2026-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='house_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='place',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
